### ISSUE TITLE
Use of RFC3339 and date-time format in JSON Schema

### ISSUE THREAD

**Issue by sevein** [JiscRDSS/rdss-message-api-specification#52]
I'd like RFC3339 to be considered instead of the ISO8601 extended format. I'm not in a position to make a recommendation though but it seems the former is the recommended option for new protocols.

JSON Schema seems to prefer RFC3339. The `date-time` format (`format` keyword) provided can be used to introduce semantic validation using RFC3339, e.g. this is how the `date` definition would look like:

```{
  "date": {
    "type": "object",
    "properties": {
      "dateValue": {
        "type": "string",
        "format": "date-time"         <------ RFC3339
      },
      "dateType": {
        "type": "number"
      }
    },
    "required": [
      "dateValue",
      "dateType"
    ]
  }
}
```

Of the three formats listed in the v1.2.0 spec there is one that it's not rfc3339-compliant.

| Format | RFC3339-compliant |
| - | - |
| `YYYY-MM-DDThh:mmTZD` | No |
| `YYYY-MM-DDThh:mm:ssTZD` | Yes |
| `YYYY-MM-DDThh:mm:ss.sTZD` | Yes |

The RAML spec seems to bring an interesting multi-format approach when it comes to dates: https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#date. They had a thoughtful discussion here https://git.io/v5w0X.

**Comment by danielgrant** [comment]
Hi @sevein, this was implemented in https://github.com/JiscRDSS/rdss-message-api-specification/commit/2cf2267a2b30f41d11561bc9644ce7fa53d8934f#diff-f6d19899418a80115b352f0f2ef5961e so I'm going to close this issue.
