### ISSUE TITLE
Improve documentation around `messageClass`

### ISSUE THREAD

**Issue by fmcc** [JiscRDSS/rdss-message-api-specification#62]
The purpose of `messageClass` should be explicitly stated in the documentation of the message API. At least the three messageClasses being used in the message api should be defined by linking to the relevant sections of "Enterprise Integration Patterns", but it would be best if their intended role within the RDSS was described. The relationship between `messageClass` and `messageType` should also be documented, as it is not at present stated e.g. that `MetadataRead` is a `Command`.

**Comment by danielgrant** [comment]
Hi @fmcc,

I've expanded on the use of `messageClass` in this pull request, which has been assigned for your review: https://github.com/JiscRDSS/rdss-message-api-specification/pull/79.

Can you take a look and let me know what you think.

Cheers,
Daniel.
