### ISSUE TITLE
Problems in message headers

### ISSUE THREAD

**Issue by sevein** [JiscRDSS/rdss-message-api-specification#69]
##### `messages/header/header_schema.json`

Under `messageTimings`:

- It reads `publishedstring` instead of `publishedTimestamp`.
- It reads `expirationstring ` instead of `expirationTimestamp`.
- It reads `pattern` instead of `format`.

Under `messageHistory`:

- It should be an `array` instead of an `object` (multiplicity is `0..*`).
- Property `string` should be `timestamp` and is missing `format`.

Cosmetic issues:

- Unneeded blank lines in L52 and L76.
- Unneeded whitespace before `:` (colon) in L29 and L33 etc...

##### `messages/header/header.json`

- `messageHistory` should be converted into an `array`.

##### `messages/message.json`

- `messageHistory` should be converted into an `array`.

**Comment by danielgrant** [comment]
Hi @sevein ,

Apologies for the mistakes here - not entirely sure how they slipped through the peer review process.

I've fixed and them and opened a pull request for your review: https://github.com/JiscRDSS/rdss-message-api-specification/pull/78.

Daniel.

**Comment by sevein** [comment]
:clap: :clap: :clap: :clap:
