### ISSUE TITLE
Specification version in README.md reads 1.2.2-SNAPSHOT instead of 1.3.0

### ISSUE THREAD

**Issue by sevein** [JiscRDSS/rdss-message-api-specification#70]
This affects `master`.

---

![image](https://user-images.githubusercontent.com/606459/34425513-62926b02-ebe1-11e7-8e3e-1cef0d69255f.png)

**Comment by danielgrant** [comment]
Hi @sevein, apologies that was an oversight on my part. Will sort it on the next release.
